package com.koala.reactingreactions.content.multiblock;

import com.koala.reactingreactions.ReactingReactions;
import com.simibubi.create.foundation.block.connected.AllCTTypes;
import com.simibubi.create.foundation.block.connected.CTSpriteShiftEntry;
import com.simibubi.create.foundation.block.connected.CTSpriteShifter;
import com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour;

import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.BlockAndTintGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;

import org.jetbrains.annotations.Nullable;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

/**
 * Create's connected textures across one machine's walls and controller, so it reads as one plate. The {@code <name>_connected}
 * sheets are generated by {@code tools/ct_sheet.py}.
 */
public final class MultiblockConnectedTextures {
    private MultiblockConnectedTextures() {
    }

    /**
     * @param family   the blocks (walls and controller) that connect to each other
     * @param textures names of the block textures the machine's models use ({@code block/<name>}); each needs a matching
     *                 {@code block/<name>_connected} sheet
     */
    public static ConnectedTextureBehaviour behaviour(Supplier<List<Block>> family, String... textures) {
        Map<ResourceLocation, CTSpriteShiftEntry> shifts = new HashMap<>();
        CTSpriteShiftEntry first = null;
        for (String name : textures) {
            ResourceLocation base = ReactingReactions.asResource("block/" + name);
            ResourceLocation sheet = ReactingReactions.asResource("block/" + name + "_connected");
            CTSpriteShiftEntry shift = CTSpriteShifter.getCT(AllCTTypes.OMNIDIRECTIONAL, base, sheet);
            shifts.put(base, shift);
            if (first == null) {
                first = shift;
            }
        }
        return new Behaviour(family, shifts, first);
    }

    private static final class Behaviour extends ConnectedTextureBehaviour.Base {
        private final Supplier<List<Block>> family;
        private final Map<ResourceLocation, CTSpriteShiftEntry> shifts;
        private final CTSpriteShiftEntry any;

        private Behaviour(Supplier<List<Block>> family, Map<ResourceLocation, CTSpriteShiftEntry> shifts, CTSpriteShiftEntry any) {
            this.family = family;
            this.shifts = shifts;
            this.any = any;
        }

        @Nullable
        @Override
        public CTSpriteShiftEntry getShift(BlockState state, Direction direction, @Nullable TextureAtlasSprite sprite) {
            // A null sprite is Create asking for the connection type only; any of this machine's sheets answers that.
            return sprite == null ? any : shifts.get(sprite.contents().name());
        }

        @Override
        public boolean connectsTo(BlockState state, BlockState other, BlockAndTintGetter reader, BlockPos pos, BlockPos otherPos, Direction face) {
            return !isBeingBlocked(state, reader, pos, otherPos, face) && family.get().contains(other.getBlock());
        }
    }
}
