package com.koala.reactingreactions.registry;

import com.koala.reactingreactions.ReactingReactions;
import com.mojang.serialization.MapCodec;

import net.minecraft.core.particles.ColorParticleOption;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/** This mod's particle types (sprites drawn by {@code tools/make_particles.py}; the descriptions are generated by datagen). */
public class CRRParticles {
    private static final DeferredRegister<ParticleType<?>> PARTICLES = DeferredRegister.create(Registries.PARTICLE_TYPE, ReactingReactions.MODID);

    /** A soft, translucent puff of toxic air or gas, in the colour (and alpha) it is given. */
    public static final DeferredHolder<ParticleType<?>, ParticleType<ColorParticleOption>> TOXIC_HAZE = PARTICLES.register("toxic_haze",
            () -> new ParticleType<ColorParticleOption>(false) {
                @Override
                public MapCodec<ColorParticleOption> codec() {
                    return ColorParticleOption.codec(this);
                }

                @Override
                public StreamCodec<? super RegistryFriendlyByteBuf, ColorParticleOption> streamCodec() {
                    return ColorParticleOption.streamCodec(this);
                }
            });

    /** Haze of {@code rgb} at {@code alpha} (0-1). */
    public static ColorParticleOption haze(int rgb, float alpha) {
        return ColorParticleOption.create(TOXIC_HAZE.get(), (Math.round(alpha * 255) << 24) | (rgb & 0xFFFFFF));
    }

    public static void register(IEventBus modEventBus) {
        PARTICLES.register(modEventBus);
    }
}
