package com.koala.reactingreactions.registry;

import com.koala.reactingreactions.ReactingReactions;

import net.minecraft.core.registries.Registries;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/** This mod's sound events (the audio is synthesised by {@code tools/make_sounds.py}; the definitions are generated by datagen). */
public class CRRSounds {
    private static final DeferredRegister<SoundEvent> SOUNDS = DeferredRegister.create(Registries.SOUND_EVENT, ReactingReactions.MODID);

    public static final DeferredHolder<SoundEvent, SoundEvent> DRILL_RUMBLE = register("drill_rumble");
    public static final DeferredHolder<SoundEvent, SoundEvent> SCRUBBER_HUM = register("scrubber_hum");
    public static final DeferredHolder<SoundEvent, SoundEvent> GAS_HISS = register("gas_hiss");
    public static final DeferredHolder<SoundEvent, SoundEvent> IGNITE_WHOOSH = register("ignite_whoosh");
    public static final DeferredHolder<SoundEvent, SoundEvent> POOL_SPLASH = register("pool_splash");
    public static final DeferredHolder<SoundEvent, SoundEvent> LEAK_DRIP = register("leak_drip");
    public static final DeferredHolder<SoundEvent, SoundEvent> VAT_BUZZ = register("vat_buzz");
    public static final DeferredHolder<SoundEvent, SoundEvent> BOILING = register("boiling");
    public static final DeferredHolder<SoundEvent, SoundEvent> OVEN_ROAR = register("oven_roar");

    private static DeferredHolder<SoundEvent, SoundEvent> register(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(ReactingReactions.asResource(name)));
    }

    public static void register(IEventBus modEventBus) {
        SOUNDS.register(modEventBus);
    }
}
