package com.koala.reactingreactions.registry;

import com.koala.reactingreactions.ReactingReactions;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.material.Fluid;

/** This mod's own tags; their contents are generated by {@code MiscData}. */
public final class CRRTags {
    /** Items that clean up a leak pool, one used up per pool. */
    public static final TagKey<Item> CLEANING_AGENTS = tag(Registries.ITEM, "cleaning_agents");
    /** Blocks that keep contamination in and count as a roof or floor for scrubbers. */
    public static final TagKey<Block> AIRTIGHT = tag(Registries.BLOCK, "airtight");
    /** Blocks that set off flammable pools and vents. */
    public static final TagKey<Block> IGNITES_TOXIC = tag(Registries.BLOCK, "ignites_toxic");
    /** Fluids the Charging Pad accepts. */
    public static final TagKey<Fluid> RECHARGEABLE = tag(Registries.FLUID, "rechargeable");

    private CRRTags() {
    }

    private static <T> TagKey<T> tag(ResourceKey<? extends Registry<T>> registry, String name) {
        return TagKey.create(registry, ReactingReactions.asResource(name));
    }
}
